name: lelele_proto1
description: Music learn application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_launcher_icons: 0.8.1

  # Firebase
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ">=0.11.0"
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.2.1+1
  firebase_storage: ^5.0.1
  firebase_admob: ^0.10.0+2
  firebase_in_app_messaging: ^0.2.3

  # Auth
  flutter_signin_button: ^1.1.0
  google_sign_in: ^4.5.6

  # UI
  flutter_slidable: "^0.5.5"
  photo_view: ^0.10.1
  table_calendar: ^2.3.1
  file_picker: ^2.0.2
  page_transition: "^1.1.7+2"
  flutter_colorpicker: ^0.3.4
  numberpicker: ^1.2.1
  local_image_provider: ^2.2.0
  auto_size_text_field: ^0.1.6
  webview_flutter: ^1.0.7
  toggle_switch: ^0.1.8


  # Sound
#  audioplayers: ^0.16.1
  audioplayers: ^0.17.0
  # 録音 動かない方のパッケージ 2020/09/20
  #  audio_recorder: ^1.0.2
  flutter_audio_recorder: ^0.5.5
  audiotagger: ^1.1.0

  path_provider: ^1.6.16
  package_info: ^0.4.3
  intl: ^0.16.1
  uuid: 2.2.2
  file: ^5.2.1


  # Util
  provider: ^4.3.2+2
  shared_preferences: ^0.5.12+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

  # 新しいテストフレームワーク
  # https://medium.com/flutter/updates-on-flutter-testing-f54aa9f74c7e
#  integration_test: ^1.0.0
#    ↑ 有効にすると file でエラーになるが、fileを以下にすると flutter_audio_recorderでエラーになるので無効にする
#   file: 6.0.0-nullsafety.2


# 2020/08/23 Add スプラッシュスクリーン用
flutter_native_splash:
  image: "assets/images/lelele_logo.png"
  color: "E64436"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  fonts:
    - family:  LeleleIcon
      fonts:
        - asset: assets/fonts/LeleleIcon.ttf


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/
    - assets/audio/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  generate: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/lelele_icon.png'
flutter_intl:
  enabled: true

#dependency_overrides:
#  intl: ^0.17.0-nullsafety.2
